# Site settings
author: Tiffany
#baseurl: "https://hungry-khorana-37eeb2.netlify.com"
baseurl: ""
brand: DDT
copyright: Dean J. Tantillo
description: For a variety of organic reaction...
email: tantillo@chem.ucdavis.edu
title: DDT 
url: ""

# Not using because Gulp is now processing SCSS
# sass:
#   sass_dir: css
#   style: compressed

# Algolia Search
algolia:
  application_id: KXQ8X1AP4V  # Use your (non-admin) search only api key here.
  index_name: DDTWeb #Use an index you created on Algolia.

# Collections
collections:
  docs:
    output: true
    permalink: "/:collection/:path/"
  posts:
    output: true
    permalink: "/:collection/:title/"

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post 
      type: post
  - scope:
      path: "pages"
      type: pages
    values:
      layout: default 
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: post
      type: doc

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "publish.sh",
  "yarn-error.log",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/page:num"
  sort_reverse: true
  title: ":title"
  trail:
    before: 2
    after: 2

# Plugins
plugins: [jekyll-paginate-v2, jemoji, jekyll-sitemap, jekyll-seo-tag]

# SEO
social:
  name: Kimfucious
  links:
    - https://github.com/yue1411
    - https://www.linkedin.com/in/tiffany-yue-zhang-219a4a13a/
webmaster_verifications:
  google: uubLfpcORmDWkM8pI-yKODVVZD3VSpUYFSwkQJcOuZE


# Social icons
show_social_icons: true
# facebook_username: 
github_username: yue1411 
googleplus_username: 
# linkedin_username: kimaford
# slack_username: 
# twitter_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
